### ISSUE TITLE
high res images for Life Cycle chapter

### ISSUE THREAD

**Issue by wibeasley** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#113]
@stephanieshong  & @bryanlaraway, the resolution of the test figure looks good.  Thanks.  Please continue with the rest of the images (and remember to keep everything lowercase).

Note that the squiggly underline (reflecting Word's spelling & grammar checks) are visible in that recent figure.  I suggest you temporarily turn them off during the screenshots.

![image](https://user-images.githubusercontent.com/1372890/236884710-ea0e26b9-cf82-48ae-be39-da3c99b5ce2d.png)

https://national-covid-cohort-collaborative.github.io/guide-to-n3c-v1/chapters/cycle.html

builds on #98

**Comment by stephanieshong** [comment]
Ah, ok. Thank you. I wanted to double check on one image to see if will be acceptable. Good thing I did.

**Comment by stephanieshong** [comment]
here is the pull request - https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/pull/114

**Comment by stephanieshong** [comment]
Rest of the images have been updated along with the figure descriptions. Let me know if there are any missing or items that need additional updates. Thanks.

**Comment by wibeasley** [comment]
@stephanieshong  & @bryanlaraway, looks great.  I just need to remove the callout, and issue #98 will be complete!
