### ISSUE TITLE
user story idea

### ISSUE THREAD

**Issue by oneilsh** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#12]
Idea: early in book, present a user story, with enough detail to hit the high points and referencing later chapters for more detail.

User story: a research team with a specific question in mind (basic 2x2 sort of test with an outcome: severe? death?), but show notional data for screenshots etc?

- Registration, have a team already, covered by DUA
- Browse enclave, check out the learning datasets, read up on OMOP
- Submit DUR for say level 2/DAC approval
- hook up with a domain team, attend one of the meetings
- Collaborators join via request/approval
- Find their project space
- interested in something, say obesity (?), have a starting ICD code
   - go to atlas, look up code, define concept set, import into N3C
- use contour to generate histogram of ages, export cohort of interest
- use person-level template (or table) to do the 2x2 based on defined outcome from the template (hosp vs non hosp?)
- produce a table of stat results & a figure
- submit download request
- draft manuscript
- submit to pub committee
- submit to journal
- get accepted, fame and fortune

**Comment by wibeasley** [comment]
replaced by #25
