### ISSUE TITLE
Section for "Cohort Definition"

### ISSUE THREAD

**Issue by wibeasley** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#126]
@oneilsh, I'm looking through the book and not seeing an explicit description of the sample (ie, every covid positive patient is retained, and up to two matched controls are retained).  Am I overlooking it?

It seems like it should be in the [Understanding the Data](https://national-covid-cohort-collaborative.github.io/guide-to-n3c-v1/chapters/understanding.html) and/or the [Data Life Cycle](https://national-covid-cohort-collaborative.github.io/guide-to-n3c-v1/chapters/cycle.html) chapters?  And maybe a super brief description in the [Introduction](https://national-covid-cohort-collaborative.github.io/guide-to-n3c-v1/chapters/intro.html)?

I started looking for this section to help Peter Robinson with [your exchange](https://docs.google.com/document/d/1YLsu1AWK86b93ak-uHKn5_10PNcxY0dkKEmLH48IQT4/edit?disco=AAAAwGuDB_Q)
> Shawn: may be worth re-mentioning that N3C data is not a random sample to begin with due to inclusion criteria
>
> Peter: Is there another chapter to which we can refer about this or do we need to write a detailed explanation?

**Comment by oneilsh** [comment]
Yeah this seems like it would go in the Data Lifecycle chapter, likely with a brief description and linking out to the phenotype definition on github: https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/wiki/Latest-Phenotype

@bryanlaraway or @stephanieshong, could you add a paragraph or so describing the phenotype?

**Comment by stephanieshong** [comment]
@oneilsh  - ok, I will take a stab at it.

**Comment by wibeasley** [comment]
during today's meeting, we talked about a "Cohort Definition" section in the lifecycle chapter

@JohannaLoomba  & @hlehmann17's advice:

* clear definition of the sampling frame
* independent of the N3C "controls", each study should manage their own controls.  This decision will be different for different research questions.
* link to Best Practices section: https://national-covid-cohort-collaborative.github.io/guide-to-n3c-v1/chapters/practices.html#research-question

**Comment by stephanieshong** [comment]
@wibeasley - where do you want me to insert brief description about the "Cohort Definition" within the Data Life Cycle?

**Comment by wibeasley** [comment]
For the record, @hlehmann17  replied:
> I would suggest as a Heading 2 subsection of Introduction, so it’s visible to readers right off the bat and through the Table of Contents.
>
>“N3C Overall Cohort Definition”

Sounds good to me.

**Comment by stephanieshong** [comment]
thank you

**Comment by stephanieshong** [comment]
N3C COVID-19 patients are defined as patient with one or more COVID-19 positive lab results or one or more strong positive diagnosis codes from the ICD-10 or SNOMED CT listed in this [table <https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/wiki/Latest-Phenotype>] or two or more "weak positive" diagnosis codes from the ICD-10 or SNOMED CT tables during the same encounter or on the same date on or prior to 5/1/2020 without age or demographic restrictions. N3C defines control cohort as patient with one or more lab test with non-positive results, at a ratio of 1:2 (cases:controls). The N3C cohort use 1/1/2020 as encounter start date. 
We recommend that analyst manage control cohorts independent of the N3C controls. Each study may have criteria that is very specific to the research question and the control cohort decision may be different for each research and N3C control cohort may not be representative to meet the standards of each research group. 
Here is a link to Best Practices section, which can be helpful. [see <https://national-covid-cohort-collaborative.github.io/guide-to-n3c-v1/chapters/practices.html#research-question>].

**Comment by stephanieshong** [comment]
@wibeasley  - feel free to update / change from what I added. I will send you the PR.

**Comment by stephanieshong** [comment]
### N3C Overall Cohort Definition {#sec-cycle-intro-cohortdef}
PR for this update - https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/pull/145
