### ISSUE TITLE
add section for DQ

### ISSUE THREAD

**Issue by wibeasley** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#130]
I think the book is missing a section on data quality.  @jerrodanzalone added a sentence in the story, but I think it needs more.

**Comment by jerrodanzalone** [comment]
@wibeasley Do you think a special chapter would make sense? I could potentially see this being an interesting discussion on the difference between data quality assessment in federated and centralized research networks. While N3C doesn't require benchmarking for participation, as is customary in PCORnet and OHDSI, the ability to directly evaluate data at the scale of N3C is novel and presents unique challenges.

**Comment by wibeasley** [comment]
That makes a lot of sense to me. Do you have a rough outline in mind?

**Comment by jerrodanzalone** [comment]
Let me think on it a little.

**Comment by hlehmann17** [comment]
I'll remind folks that N3C has published a paper on this issue: https://pubmed.ncbi.nlm.nih.gov/34590684/

**Comment by jerrodanzalone** [comment]
@hlehmann17 Good point, but that paper covers the topic at the data harmonization phase. We are talking about at the study level within the Enclave. So this could build upon the work of the LL group with the data quality templates as well as other special considerations developed by the domain teams over the last few years.

**Comment by wibeasley** [comment]
@hlehmann17, that paper is already referenced in @jerrodanzalone's and my chapter here

https://national-covid-cohort-collaborative.github.io/guide-to-n3c-v1/chapters/story.html#fnref23

![image](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/1372890/6c2f4de8-06f3-4a64-aa9e-b4abb63a0c89)

It's also in these three places.
* https://national-covid-cohort-collaborative.github.io/guide-to-n3c-v1/chapters/cycle.html#sec-cycle-releases-lds
* https://national-covid-cohort-collaborative.github.io/guide-to-n3c-v1/chapters/understanding.html#sec-understanding-public
* https://national-covid-cohort-collaborative.github.io/guide-to-n3c-v1/chapters/support.html#sec-support-liaisons

**Comment by hlehmann17** [comment]
Got it. Was not a criticism, just wanted to save folks some work!

**Comment by hlehmann17** [comment]
I would point out that if we develop a "theory" of study-specific data quality checks, we could, perhaps, develop the sequence in Protocol Pad, giving it a bit more "teeth" than just a chapter.

**Comment by JohannaLoomba** [comment]
Discussed 6/5.  Another idea would be to cover this in a chapter devoted to sample project with tie-ins to chapters where quality tools and data considerations are covered.

**Comment by wibeasley** [comment]
I'm closing the issue after talking through it in today's meeting.  When we add a chapter for a sample project, @JohannaLoomba  & @hlehmann17 recommend it includes a section on DQ too.
