### ISSUE TITLE
"Enclave" or "enclave" capitlization

### ISSUE THREAD

**Issue by wibeasley** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#133]
Should the first *e* be capitalized?  I thought it was, but the Help & Support chapter uses a lowercase e.

There are a lot of stylistic things that are fine if chapters do differently (as long as it's consistent within the chapter).  But I think this should be consistent across chapters.  

Do people have thoughts on upper & lower case?  On capitalizing it consistently across chapters?

<https://covid.cd2h.org/enclave>
![image](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/1372890/82ccd15c-e26e-4e01-a3ef-dcac3b030c12)

<https://national-covid-cohort-collaborative.github.io/guide-to-n3c-v1/chapters/support.html>

![image](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/1372890/278c2bc4-4992-4785-96c1-7a1c57bf2f65)

**Comment by JohannaLoomba** [comment]
Per Julie and team: First mention in a paragraph/section should be N3C Data Enclave then after that Enclave is ok (in the vicinity).  Thanks!

**Comment by wibeasley** [comment]
@JohannaLoomba, ok.  I'll go through the book and add the qualifier where it's needed.  I don't think it's necessary to involve the individual authors.

So is it always a capital "E"?  (For both the section's first and subsequent appearances?)

**Comment by JohannaLoomba** [comment]
Yes, the idea was always capital E and spell it out in full at start of any chapter where it is mentioned before shortening to Enclave.

**Comment by wibeasley** [comment]
@JohannaLoomba & @jmcmurry, I got all of them for the existing chapters.  There were a lot of "N3C Enclave" occurrences that I changed to either "N3C Data Enclave" or just "Enclave"
