### ISSUE TITLE
email for correspondence

### ISSUE THREAD

**Issue by wibeasley** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#161]
@oneilsh, this is from the [home page](https://national-covid-cohort-collaborative.github.io/guide-to-n3c-v1/).    I barely remember this.  Were you going to ask for an email account that would forward to you, me, and the rest of the editorial committee?

![image](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/1372890/e64a1ec7-38be-4b45-8a85-34bf8ff680c0)

**Comment by chrisroederucdenver** [comment]
Still needed. @oneilsh

**Comment by oneilsh** [comment]
Found it, it's live, g2n3c-team@ctsa.io
