### ISSUE TITLE
Ch 3 links point to old google docs

### ISSUE THREAD

**Issue by oneilsh** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#174]
Some of the links in Ch 3 point to google docs draft chapters rather than internally to other book sections

**Comment by chrisroederucdenver** [comment]
- In section 3.5.5 the link to Public/External datasets
- 3.5.6 has Understanding the Data chapter
- 3.5.7 also has a bad link to Understanding the Data
- 9.4.53 has a link called "here" to the special topics appendix chapter in google

**Comment by chrisroederucdenver** [comment]
fixed by PR #180
