### ISSUE TITLE
selecting license

### ISSUE THREAD

**Issue by wibeasley** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#18]
During the editorial committee meeting, we were favoring [CC-BY-ND-4.0](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#definitionslicense-enum).  
- [ ] I'll add that to [cff file](https://github.com/National-COVID-Cohort-Collaborative/book-of-n3c-v1/blob/main/CITATION.cff) and the [license file](https://github.com/National-COVID-Cohort-Collaborative/book-of-n3c-v1/blob/main/LICENSE) and  (from https://github.com/idleberg/Creative-Commons-Markdown/blob/master/4.0/by-nd.markdown)
- [ ] @oneilsh is talking to NIH people about it

**Comment by oneilsh** [comment]
I think we can close this one yeah?

**Comment by wibeasley** [comment]
agreed at the last committee meeting
