### ISSUE TITLE
"Chapter in Progress" call out

### ISSUE THREAD

**Issue by wibeasley** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#185]
@chrisroederucdenver, while you and @oneilsh are putting the final touches on the chapter, I'm going to add a callout like this to give you a little breathing room from readers.  When you're happy with the finished product, I'll remove the call out.

```quarto
:::{.callout-note} This material for this chapter is mostly complete,
and we're adding the final touches before officially publishing it.

In the meantime, please enjoy this pre-release version.
:::
```

**Comment by chrisroederucdenver** [comment]
So glad to see this move along and to be a part of it. Up to now, i'd only heard about the book, and don't remember getting the link. Maybe I got the link and put off reading it thinking I'd wait until it was finished.

So I'm working through it now, and it's really useful. Thanks!
