### ISSUE TITLE
Ch. 13 ML link to VaTech for ML in N3C

### ISSUE THREAD

**Issue by chrisroederucdenver** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#191]
Seems like we could use a link here:
data transform code repository that Blessy Antony (Virginia Tech, blessyantony@vt.edu) developed to do machine learning in N3C.

Also, the github links before and after that quote point to the same thing.

**Comment by justaddcoffee** [comment]
Thanks Chris for the sharp eyes

I think we did originally have a link just after the phrase "For our walkthrough, we will be creating and using a Python library repository " to [this](https://unite.nih.gov/workspace/data-integration/code/repos/ri.stemma.main.repository.aee54470-95fb-4d9c-b694-94480f171c74/contents/refs%2Fheads%2Fmaster/src/models/sklearn/classification_model.py) repo in N3C, but someone (Shawn I think?) pointed out that some readers of the chapter might not be able to see this, thus the github link

**Comment by chrisroederucdenver** [comment]
Thanks

The way I read the text, are you talking about two different code projects? Or are ml-classification-pipeline and Blessy's the same just in different places (github and N3C enclave)? In either case the enclave link might be useful even if it's locked.

Case in point, I don't have perms to the N3C repo you linked above.

**Comment by justaddcoffee** [comment]
> The way I read the text, are you talking about two different code projects? Or are ml-classification-pipeline and Blessy's the same just in different places (github and N3C enclave)? In either case the enclave link might be useful even if it's locked.

The github repo and Enclave link are essentially the same code I believe

@oneilsh can you comment about whether we should link to (possibly 404) links to Enclave resources? No strong feelings, but possibly the G2N3C people have decided an SOP here that we can follow

**Comment by justaddcoffee** [comment]
> I have a commit (PR to follow) that includes the link to the N3C enclave repo and uses it.
I removed the (IMHO) redundant github link, and it looks like this:

Sounds good to me! Thanks Chris. I assume you won't need me to merge this PR?
