### ISSUE TITLE
Rough Images in ML chapter

### ISSUE THREAD

**Issue by chrisroederucdenver** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#193]
Some images for the ML chapter are low-res and impossible or very hard to read: 1, 4, 6, 7, 8, 9, 11

5, 10 are borderline. 2 and 3 are awesome.

**Comment by oneilsh** [comment]
I've updated 4 through 9, I should be able to fix 1 (missed it first time around) @justaddcoffee could you help with sourcing higher-res versions of 10 and 11?

**Comment by justaddcoffee** [comment]
I'll see if I can track down a better version of 10 and 11 ([here](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/blob/main/chapters/images/ml/image-10-referencing-nodes-codeworkbook.png) and [here](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/blob/main/chapters/images/ml/image-11-viewing-visualization-outputs.png) right?)


@ElenaCasiraghi do you happen to have a highres copy of these?

**Comment by chrisroederucdenver** [comment]
Anyone for #1? The rest are all in and look good!

**Comment by oneilsh** [comment]
Here's an updated figure for that one: 

I haven't created a PR yet cuz I'm waiting for my other one and don't want to muck up git again lol

<img width="1364" alt="image-01-create-folder-in-workspace" src="https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/77859/921983a1-7312-4101-b450-be11391b62b5">

**Comment by chrisroederucdenver** [comment]
closed with the last image!
