### ISSUE TITLE
Ch. 13, ML, do figures correctly

### ISSUE THREAD

**Issue by chrisroederucdenver** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#194]
Questions. (using an issue to get attention)

- I haven't seen figures in ML work where you click on them and get a higher resolution pop-up. Looking, but do you know what I might be missing?

- I'm looking at how the other chapters get auto numbering on the "Figure n" captions...

**Comment by wibeasley** [comment]
I'm not sure why the "lightbox" filter (which was @oneilsh's idea to use in issue #20) isn't working for your chapter.

In the meantime, can you move the chapter's images into the standard place.  Notice each chapter has a separate/dedicated directory to hold their images: https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/tree/main/chapters/images

**Comment by chrisroederucdenver** [comment]
> In the meantime, can you move the chapter's images into the standard place. Notice each chapter has a separate/dedicated directory to hold their images: https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/tree/main/chapters/images

Images were moved this morning in this commit: https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/commit/f966da37d1816a6e26a5cb6558f753986a1ccec1
in this PR: https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/pull/192

**Comment by chrisroederucdenver** [comment]
> I'm not sure why the "lightbox" filter (which was @oneilsh's idea to use in issue #20) isn't working for your chapter.
Lovely. I see the figure and figcaption in the HTML for other chapters. Looking.

**Comment by chrisroederucdenver** [comment]
Work-arounds display like you might expect them.
