### ISSUE TITLE
ML chapter authors block needs adjustment

### ISSUE THREAD

**Issue by oneilsh** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#206]
@justaddcoffee - can you fix up the author block for the ML chapter at the top of the file? Check out one of the other chapters for an example, we're hoping for those 5 pieces of info for all contributors (name, email, orcid, affiliation, affiliation-url for each of Peter Robinson, Justin Reese, Blessy Antony, T.M. Murali, Elena Casiraghi, Hannah Blau).

I believe that will list all of the contributors at the top (including orcid links once that is fixed by PR #205 ). Then under the chapter heading the `**Chapter Leads:**` can be edited to include just the main leads for the chapter - which I think is just you and Peter for this one, but if you want to expand that list you can.

Thanks!

**Comment by justaddcoffee** [comment]
hi @oneilsh, sure glad to help 

I believe this are the correct info for everyone:

Peter's formal/publishing name: Peter N Robinson
Peter's preferred public email to be listed: peter.robinson@bih-charite.de
Peter's ORCiD: 0000-0002-0736-9199
Peter's affiliation: Berlin Institute of Health at Charité
Peter's affiliation’s url: https://www.bihealth.org/

Justin's formal/publishing name: Justin Reese
Justin's preferred public email to be listed: justinreese@lbl.gov
Justin's ORCiD: 0000-0002-2170-2250
Justin's affiliation: Lawrence Berkeley National Laboratory
Justin's affiliation’s url: https://biosciences.lbl.gov/profiles/justin-reese/

Blessy's formal/publishing name: Blessy Antony
Blessy's preferred public email to be listed: blessyantony@vt.edu
Blessy's ORCiD: 0000-0002-1269-5191
Blessy's affiliation: Virginia Tech
Blessy's affiliation’s url: https://cs.vt.edu/

Elena's formal/publishing name: Elena Casiraghi
Elena's preferred public email to be listed: [elena.casiraghi@unimi.com](mailto:elena.casiraghi@unimi.com) - [ECasiraghi@lbl.gov](mailto:ECasiraghi@lbl.gov)
Elena's ORCiD: 0000-0003-2024-7572
Elena's affiliation: Università degli Studi di Milano / 
Elena's affiliation’s url: https://casiraghi.di.unimi.it/

David formal/publishing name: David Sahner
David preferred public email to be listed: david.sahner@nih.gov
David ORCiD: 0000-0002-4616-1171
David’s affiliation: National Center for Advancing Translational Sciences
David’s affiliation’s url: https://ncats.nih.gov/

TM's formal/publishing name: T. M. Murali
TM's preferred public email to be listed: murali@cs.vt.edu
TM's ORCiD: 0000-0003-3688-4672
TM's affiliation: Virginia Tech
TM's affiliation’s url: https://bioinformatics.cs.vt.edu/~murali/

Hannah's formal/publishing name: Hannah Blau
Hannah's preferred public email to be listed: hannah.blau@jax.org
Hannah's ORCiD: 0000-0003-4557-5492
Hannah's affiliation: The Jackson Laboratory for Genomic Medicine
Hannah's affiliation’s url: https://www.jax.org/

Not sure exactly where to put this though

**Comment by justaddcoffee** [comment]
@oneilsh hope #213 is what we need here

**Comment by wibeasley** [comment]
@justaddcoffee, thanks for the PR.  Will you update the "Chapter Leads" line?  It's likely just you and Peter.

**Comment by justaddcoffee** [comment]
@wibeasley sure see #216
