### ISSUE TITLE
Move upcoming topics

### ISSUE THREAD

**Issue by oneilsh** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#207]
It's currently chapter 12 in between help and support and ML. Maybe it should be moved to back matter or removed? @wibeasley ?

**Comment by wibeasley** [comment]
Agreed.  https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/commit/28b2da10a861bf416d5eb15331e7e0497c35a584
