### ISSUE TITLE
RWD data blurbs to be added to each chapter

### ISSUE THREAD

**Issue by wibeasley** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#243]
After authors have 2 weeks to review these new RWD blurbs, I'll add convert them to markdown and add to the text. (starting around Aug 26).

- [x] Make sure to bump the [release version](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/releases) to 1.1 (which also creates a new Zenodo).

https://docs.google.com/document/d/1UzvPGhosXfEUaebAqmMmuZMpfaNRRi9YRjz_wLsm0k8/edit

- [x] Chapter 1: Introduction
- [x] Chapter 2: A Research Story (Overview)
- [x] Chapter 3: Data Life Cycle - From Patients to N3C Researchers
- [x] Chapter 4: Governance, Leadership, and Operations Structures
- [x] Chapter 5: Onboarding, Enclave Access, N3C Team Science
- [x] Chapter 6: Getting & Managing Data Access
- [x] Chapter 7: Understanding the Data
- [x] Chapter 8: Introducing Enclave Analysis Tools
- [x] Chapter 9: Best Practices and Important Data Considerations
- [x] Chapter 10: Publishing & Sharing your Work
- [x] Chapter 11: Help & Support
- [x] Chapter 12: (Machine Learning)

example:
![image](https://github.com/user-attachments/assets/105a8cb7-92df-47d6-98c1-3d176796a8ef)

**Comment by oneilsh** [comment]
Hey @wibeasley, I added the blurbs to the markdown in the [rwdblurbs](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/tree/rwdblurbs) branch. 

I'm not sure how to bump the version though - want to push this one over the finish line?

**Comment by wibeasley** [comment]
Met w/ @oneilsh this morning.  Issue closed w/ PR #245
