### ISSUE TITLE
Chapters to Process

### ISSUE THREAD

**Issue by wibeasley** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#58]
- [x] #84
- [x] #59
- [x] #25
- [x] #98
- [x] #61
- [x] #45
- [x] #74
- [x] #100
- [x] #56
- [x] #138
- [x] #93
- [x] #48
- [x] #189
- [x] References
- [x] #87
- [x] #65 

See also
https://docs.google.com/spreadsheets/d/18FWdK1jJXZxhB4t_CKyAHPWkSWIfg5kVcR0vF4_iqlI/edit#gid=0

**Comment by chrisroederucdenver** [comment]
@wibeasley ml-updates branch has ML progress.
