### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by wibeasley** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#64]
To watch page counts and other things that might help justify our time.

Besides @oneilsh, is there anyone else who would like access?  @jmcmurry?

References:
* https://quarto.org/docs/publishing/github-pages.html
* https://analytics.google.com/analytics/web/

**Comment by jmcmurry** [comment]
yes please :)

**Comment by jmcmurry** [comment]
oh and also new comms person Taylor Dupree (might not be on GitHub yet)

**Comment by wibeasley** [comment]
The basics are operational.  Open a new issue if someone wants to do more.

![image](https://user-images.githubusercontent.com/1372890/225516207-f9ab4ebe-e476-43f1-a85d-6e0188903264.png)
